Improve the documentation
slowlydev/f1-dash pull request #114
Opened 2024-06-13 15:15 UTC by SpatzlHD

As discussed in the discord server here are some updates to the readme files of the whole project and the live-backend. I also renamed the example.env files to the more common .env.example format and updated the content of the example files to match the required env variables. I also changed the .dockerignore files to ignore the .env.example files as well

2024-06-13 15:59 UTC, slowlydev requested changes
Thanks for the PR :)
Found one or two things.

2024-06-13 15:59 UTC, slowlydev commented on dash/.dockeringore
>  example.env
Any reason why you did not remove the old entry?

2024-06-13 15:59 UTC, slowlydev commented on dash/.env.example
> +NEXT_PUBLIC_LIVE_SOCKET_URL=
Any reason why you removed the default values?

2024-06-13 15:59 UTC, slowlydev commented on live-backend/.env.example
> +LOG_LEVEL=info
The logging has changed since and I didn't update example.env so this is the new way:
```suggestion
RUST_LOG="live_backend=debug,info"
```

2024-06-13 15:59 UTC, slowlydev commented on live-backend/readme.md
> +https://techexpert.tips/windows/installing-timescaledb-windows/
Any reason you went with this and not just a docker container?

```bash
docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg16
```

2024-06-15 15:03 UTC, SpatzlHD commented on dash/.dockeringore
>  example.env
i don't really know removed them in the new commit

2024-06-15 15:03 UTC, SpatzlHD commented on dash/.env.example
> +NEXT_PUBLIC_LIVE_SOCKET_URL=
no added them back in the latest commit

2024-06-15 15:06 UTC, SpatzlHD commented on live-backend/readme.md
> +https://techexpert.tips/windows/installing-timescaledb-windows/
no reason at all I just added what saved me as i am not running the db ob docker noticed that not everyone wants to install postgres and timescale db on windows after creating the pr i removed that part from the readme file

2024-06-16 13:24 UTC, slowlydev approved these changes
Okay lgtm, thanks you for the changes 🚀

2024-06-16 13:26 UTC, merged