feature/race-control-chime
slowlydev/f1-dash pull request #188
Opened 2024-11-28 14:06 UTC by Ellodev

uses settingsStore to store the setting.
compares time of message to local time to determine if message is older than when the user went on the website. gives every message a id so that it isnt played twice.

2024-11-28 19:55 UTC, slowlydev requested changes
Thanks a lot for the PR 🙏🏻
There's a couple things that u might want to look into.

2024-11-28 19:55 UTC, slowlydev commented on dash/src/components/RaceControlMessage.tsx
> +					const parsedSettings = JSON.parse(customSettings);
With the settings store this works a bit differently now.
There's no need for getting local storage and parsing

You can do the following near the top of the component 

```ts
const raceControlChime = useSettingsStore((state) => state. raceControlChime));
```

And then use that to do your check

2024-11-28 19:55 UTC, slowlydev commented on dash/src/components/RaceControlMessage.tsx
> +						audio.play();
Would it be possible we do this once and just play the audio here? Im not sure but I feel like that would be better than loading it over and over.

2024-11-28 19:55 UTC, slowlydev commented on dash/src/components/RaceControlMessage.tsx
> +						console.log("played audio")
Please remove the console log for prod thanks :)

2024-11-28 19:55 UTC, slowlydev commented on dash/src/components/RaceControlMessage.tsx
>  export function RaceControlMessage({ msg, gmtOffset }: Props) {
Would it be possible to write the code in the `RaceControl` component? So audio just gets loaded there?

2024-11-29 11:37 UTC, Ellodev commented on dash/src/components/RaceControlMessage.tsx
> +					const parsedSettings = JSON.parse(customSettings);
I changed it 👍

2024-11-29 11:38 UTC, Ellodev commented on dash/src/components/RaceControlMessage.tsx
> +						audio.play();
I added it in the beginning of the file so it should only load once

2024-11-29 11:38 UTC, Ellodev commented on dash/src/components/RaceControlMessage.tsx
> +						console.log("played audio")
Done 👍

2024-11-29 11:39 UTC, Ellodev commented on dash/src/components/RaceControlMessage.tsx
>  export function RaceControlMessage({ msg, gmtOffset }: Props) {
I tried to add it in the RaceControl Component but havent managed to. I changed the other things you asked me to change and I'll look at this one later.

2024-11-29 19:16 UTC, slowlydev reviewed
Okay so the code is fine for me like this. If u want to you cold add a volume slider in the settings so the users can adjust the volume to their liking. I think that would be a neat addition and fairly straight forward to implement.

2024-12-05 09:33 UTC, slowlydev requested changes
Thank you for adding the volume slider, I am starting to like it. Just a few minor adjustments and we are ready to :shipit:

2024-12-05 09:33 UTC, slowlydev commented on dash/src/components/Input.tsx
> +		const value = v;
Is there any reason for this separate const? If not I would prefer that you would remove it and use v everywhere instead, you could also rename v to value, so its easier to know what this variable is about.

2024-12-05 09:33 UTC, slowlydev commented on dash/src/components/Input.tsx
> +export default function Input({ value, setValue }: Props) {
As this Input has custom code for numbers, maybe it would be a good idea to either call it numeric input or move the numeric logic to where its used, what do you think is best?

2024-12-05 09:33 UTC, slowlydev commented on dash/src/components/Slider.tsx
> +		<>
Please remove this React Fragment as Fragments are only needed when returning multiple elements where react wants just one. Read more about it here: https://react.dev/reference/react/Fragment

2024-12-05 09:33 UTC, slowlydev commented on dash/src/components/Slider.tsx
> +				id="default-range"
Please remove this id as its not needed

2024-12-05 09:33 UTC, slowlydev commented on dash/src/components/Slider.tsx
> +				className="h-2 w-full cursor-pointer appearance-none rounded-lg bg-gray-200 dark:bg-gray-700"
maybe its possible to style the slider so it uses the purple of the toggle as the know of the slider, what do you think?

2024-12-07 12:50 UTC, Ellodev commented on dash/src/components/Slider.tsx
> +				className="h-2 w-full cursor-pointer appearance-none rounded-lg bg-gray-200 dark:bg-gray-700"
I found a way to do it using tailwind accent- but sadly it seems to only work on Chrome, not sure if it works on Safari. Should I try and add it using html <style> attribute or would you rather we just add it for Chrome or not at all.

2024-12-07 12:52 UTC, Ellodev commented on dash/src/components/Input.tsx
> +export default function Input({ value, setValue }: Props) {
I'm thinking we could maybe call it something like PercentageInput since its defined as a Maximum of 100, and used for Percentages. Do you agree or would you rather that I move the Number logic somewhere else to make it more reusable?

2024-12-07 13:07 UTC, Ellodev commented on dash/src/components/Slider.tsx
> +	}
sounds good

2024-12-07 13:08 UTC, Ellodev commented on dash/src/components/Slider.tsx
> +				id="default-range"
done

2024-12-08 09:09 UTC, slowlydev commented on dash/src/components/Slider.tsx
> +				className="h-2 w-full cursor-pointer appearance-none rounded-lg bg-gray-200 dark:bg-gray-700"
On the https://tailwindcss.com/docs/accent-color page it seems to be working for me on safari as well, so I think we just add it for now and fix it for other browsers later

2024-12-08 09:10 UTC, slowlydev commented on dash/src/components/Input.tsx
> +export default function Input({ value, setValue }: Props) {
I think we go for Input for now and move the number logic to the settings page where we update the store

2025-01-09 08:13 UTC, merged