feat: add circuit sectors
slowlydev/f1-dash pull request #88
Opened 2024-04-10 20:27 UTC by tooboredtocode

This PR adds a coloured circuit/sectors.

The way the track is split into parts is a bit ugly though, when have time I might create custom components for the tracks with proper sectors, marshal sectors and the pitlane.

2024-04-14 13:01 UTC, slowlydev requested changes
Thanks a lot for this cool PR, I appreciate it a lot.
I added a few things, just some minor things...

2024-04-14 13:04 UTC, slowlydev commented
I also saw on your github profile that u code a lot of rust, If u want to I would appreciate if you could take a look at the [feature/v2 ](https://github.com/slowlydev/f1-dash/tree/feature/v2) branch where I rewrote the backend in rust, Im sure there is some room for improvement for my rust code.

2024-04-14 15:25 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +	for (let i = 0; i < data.marshalSectors.length; i++) {
We're looping, so no...

2024-04-14 15:25 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +	for (let i = 0; i < dividers.length; i++) {
We're looping, so no...

2024-04-14 15:25 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +const createSectors = (data: MapType) => {
done

2024-04-14 15:25 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +			{<>{
done

2024-04-14 15:26 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +	// @ts-ignore
my bad, that was before I added "RED" to the avaliable flag colours

2024-04-14 15:26 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +const sector_color = (sector: number, messages: RaceControlMessageType[] | undefined) => {
done

2024-04-14 16:28 UTC, slowlydev commented on dash/src/components/Map.tsx
> +	for (let i = 0; i < data.marshalSectors.length; i++) {
Ah right my bad, I am too used to "for...in" and "for...of" loops... .-.

2024-04-14 18:21 UTC, tooboredtocode commented
@slowlydev im trying to test some things, do you have any data I can use with the simulator, preferably with all possible situations (red flag, VSC, yellow flag, etc.)?

2024-04-14 19:34 UTC, slowlydev commented
> @slowlydev im trying to test some things, do you have any data I can use with the simulator, preferably with all possible situations (red flag, VSC, yellow flag, etc.)?

I don't have a synthetic file for all possible situations. But here are some files form data-saver.

https://github.com/slowlydev/f1-dash-data-parser/releases/tag/data

I also got some data from Japan but only started "recording" during the redflag. And I noticed that the sectors where the crash happened (and where yellow flags were once) were still white when the rest of the track is red.

2024-04-15 00:54 UTC, tooboredtocode commented on dash/src/components/Map.tsx
> +		return "#ffff14";
switched to tailwind colors

2024-04-15 00:55 UTC, tooboredtocode commented
Fixed the issues by syncing the track color to the trackState and only falling back to the raceControlMessages to figure out which sectors are yellow

2024-04-15 18:29 UTC, slowlydev requested changes
Thanks for the adjustments :)
Added some more comments, I like that we are using the track status now, feels a lot cleaner this way.

2024-04-15 18:42 UTC, tooboredtocode commented on dash/src/lib/getTrackStatusMessage.ts
> +	pulse?: number;
I was testing, adding it for the various safety cars, however I wasn't really satisfied with it, nor sure if ppl would like it, so I removed the setting. However I thought that deleting the code would be a shame, perhaps it is something that could be interesting...

2024-04-15 19:28 UTC, tooboredtocode commented
Cleaned the code up a bit, we now use an effect to calculate everything. Which is definitely much cleaner

2024-04-15 19:34 UTC, slowlydev commented on dash/src/lib/getTrackStatusMessage.ts
> +	pulse?: number;
Okay yeah I also find it a interesting idea, I guess we can leave it for now.

2024-04-20 08:34 UTC, slowlydev approved these changes
Sorry thought we had pending requested changes, but just went through the changes again and it looks all good. 🎉

2024-04-20 08:37 UTC, merged